# Generated by Django 4.1.1 on 2022-09-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list',
            new_name='owning_list',
        ),
    ]
