# Generated by Django 4.1.1 on 2022-09-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_to_do_list', '0002_list_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='description',
        ),
    ]
