# Generated by Django 4.1.1 on 2022-09-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_to_do_list', '0002_rename_list_item_owning_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='owning_list',
            new_name='list',
        ),
    ]
