# Generated by Django 4.1.1 on 2022-09-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_to_do_list', '0004_list_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(default='-', max_length=500),
        ),
    ]
